sudo: false
language: node_js

node_js:
    - 'lts/*'

cache:
    directories:
        - node_modules

install:
    - yarn install

addons:
    firefox: latest

script:
    - yarn lint
    - yarn build
